In [1]:
import numpy as np

In [25]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='int')
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [5]:
# Extract the first 2 rows and 2 columns
arr2[:2, :2]
#list2[:2, :2]  # error

array([[1., 2.],
       [3., 4.]])

In [4]:
# Extract the first 3 rows and 2 columns
print(arr2)
arr2[:2, :3]


[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
print(arr2)
arr2[1:1, 1:3]

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


array([], shape=(0, 2), dtype=int32)

In [9]:
# Extract the first 2 rows and 4 columns
arr2[:2, :3]

array([[1., 2., 3.],
       [3., 4., 5.]])

In [9]:
## wrong way
list2[:2, :2]

TypeError: list indices must be integers or slices, not tuple

In [11]:
## boolean output
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
## get the value of the list
print(arr2)
print('\n')
print(arr2[b])

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


[5 6 5 6 7 8]


In [22]:
## get the value of the list, condition for false
print(arr2)
print('\n')
print(arr2[b==0])

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


[1 2 3 4 3 4]


In [14]:
## reverse the row
print(arr2)

arr2[::-1, ]

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

In [17]:
# revers only the col
print(arr2)

arr2[::,::-1 ]

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


array([[4., 3., 2., 1.],
       [6., 5., 4., 3.],
       [8., 7., 6., 5.]])

In [15]:
## reverse the rows and col
arr2[::-1, ::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

In [46]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype = float)
arr22 = arr2

In [47]:
## induce missing and infinte value
import numpy as np
print(arr22)
#arr2[1,1] = np.nan
arr2[1,1] = np.nan  # not a number
print("\n")
arr2[1,2] = np.inf  # infinite

print(arr2)

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


[[ 1.  2.  3.  4.]
 [ 3. nan inf  6.]
 [ 5.  6.  7.  8.]]


In [48]:
np.isnan(arr2)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [49]:
np.isinf(arr2)

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [51]:
## # Replace nan and inf with -1. 
## Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
print(missing_bool)

print(arr2[missing_bool])
arr2[missing_bool] = -1  
print(arr2)

[[False False False False]
 [False  True  True False]
 [False False False False]]
[nan inf]
[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]


In [20]:
# # mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  3.5833333333333335
Max value is:  8.0
Min value is:  -1.0


In [21]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

Column wise minimum:  [ 1. -1. -1.  4.]
Row wise minimum:  [ 1. -1.  5.]


In [57]:
# Row wise and column wise max
print("Column wise max: ", np.amax(arr2, axis=0))
print("Row wise max: ", np.amax(arr2, axis=1))

Column wise max:  [5. 6. 7. 8.]
Row wise max:  [4. 6. 8.]


In [53]:
# Row wise and column wise mean
print("Column wise mean: ", np.mean(arr2, axis=0))
print("Row wise mean: ", np.mean(arr2, axis=1))

Column wise minimum:  [3.         2.33333333 3.         6.        ]
Row wise minimum:  [2.5  1.75 6.5 ]


In [54]:
# Row wise and column wise median
print("Column wise median: ", np.median(arr2, axis=0))
print("Row wise meadin: ", np.median(arr2, axis=1))

Column wise median:  [3. 2. 3. 6.]
Row wise meadin:  [2.5 1.  6.5]


In [55]:
# Row wise and column wise std
print("Column wise std: ", np.std(arr2, axis=0))
print("Row wise std: ", np.std(arr2, axis=1))

Column wise std:  [1.63299316 2.86744176 3.26598632 1.63299316]
Row wise std:  [1.11803399 2.94745653 1.11803399]


In [58]:
# Cumulative Sum
print(arr2)
print(np.cumsum(arr2))


[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]
[ 1.  3.  6. 10. 13. 12. 11. 17. 22. 28. 35. 43.]


In [59]:
## create a new array form an existing one

# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]  
print(arr2a)

print(arr2a[:1, :1])

## replace the above position 1st element with 100
arr2a[:1, :1] = 100  
print(arr2a)
#arr2


[[ 1.  2.]
 [ 3. -1.]]
[[1.]]
[[100.   2.]
 [  3.  -1.]]


In [24]:
# Flatten it to a 1d array
arr2.flatten()

array([ 1.,  2.,  3.,  4.,  3., -1., -1.,  6.,  5.,  6.,  7.,  8.])

In [29]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 100  # changing b1 does not affect arr2
print(arr2)
print(b1)

[[101.   2.   3.   4.]
 [  3.  -1.  -1.   6.]
 [  5.   6.   7.   8.]]
[100.   2.   3.   4.   3.  -1.  -1.   6.   5.   6.   7.   8.]


In [28]:
arr22 = arr2
# Changing the raveled array changes the parent also.
b2 = arr22.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
print(arr22)
print(b2)

[[101.   2.   3.   4.]
 [  3.  -1.  -1.   6.]
 [  5.   6.   7.   8.]]
[101.   2.   3.   4.   3.  -1.  -1.   6.   5.   6.   7.   8.]
