In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import statsmodels.api as sm
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix #Evaluation of model
from sklearn.datasets import load_diabetes
from sklearn.metrics import roc_curve,roc_auc_score

In [30]:
from sklearn.datasets import load_iris

In [31]:
load_iris

<function sklearn.datasets.base.load_iris(return_X_y=False)>

In [32]:
ir=load_iris()

In [33]:
ir.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
iris=pd.DataFrame(ir.data)

In [35]:
iris.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [36]:
iris.columns=ir.feature_names

In [37]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [38]:
iris.nunique()

sepal length (cm)    35
sepal width (cm)     23
petal length (cm)    43
petal width (cm)     22
dtype: int64

In [39]:
iris['species']=ir.target

In [40]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [41]:
from sklearn.neighbors import KNeighborsClassifier

In [42]:
model=KNeighborsClassifier() #model=KNeighborsClassifier(n_neighbours=15) 

In [43]:
x=iris.drop("species",axis=1)
y=iris.species

In [44]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=1/3, random_state=0)

In [45]:
model.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
pred=model.predict(xtest)

In [47]:
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2])

In [48]:
accuracy_score(ytest,pred)

0.98

- If we have categorical values we encode them to numerical values using encoder

syntax given below

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
encode_target=le.fit_transform(iris.columnname)

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [51]:
k_list = list(range(1,50,2))
cv_scores=[]

for k in k_list: 
    knn=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(knn, xtrain, ytrain, cv=10, scoring='accuracy')
    cv_scores.append(scores.mean())

In [52]:
from sklearn.naive_bayes import GaussianNB

In [53]:
gmodel=GaussianNB()

In [54]:
gmodel.fit(xtrain,ytrain)

GaussianNB(priors=None, var_smoothing=1e-09)

In [55]:
gpred=gmodel.predict(xtest)

In [56]:
gpred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2])

In [57]:
accuracy_score(ytest,gpred)

0.96

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
dtmodel=DecisionTreeClassifier()

In [60]:
dtmodel.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [61]:
dtpred=dtmodel.predict(xtest)

In [62]:
dtpred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2])

In [63]:
accuracy_score(ytest,dtpred)

0.98

In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
rfmodel=RandomForestClassifier()

In [66]:
rfmodel.fit(xtrain,ytrain)

C:\Users\Sebastian john\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [67]:
rdpred=rfmodel.predict(xtest)

In [68]:
rdpred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2])

In [69]:
accuracy_score(ytest,rdpred)

0.96